// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package server

// Defines values for HealthStatusDatabase.
const (
	HealthStatusDatabaseOK HealthStatusDatabase = "OK"
)

// Defines values for HealthStatusServer.
const (
	HealthStatusServerOK HealthStatusServer = "OK"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Database *HealthStatusDatabase `json:"database,omitempty"`
	Server   HealthStatusServer    `json:"server"`
}

// HealthStatusDatabase defines model for HealthStatus.Database.
type HealthStatusDatabase string

// HealthStatusServer defines model for HealthStatus.Server.
type HealthStatusServer string
